### ISSUE TITLE
Telnet

### ISSUE THREAD

**Issue by kkberg** [MajenkoProjects/WiFiSerialDTR#1]
Hello, how is status about telnet connection to host? I'm looking for a solution to configure wifi settings without using Arduiono IDE.

Thank you very much

**Comment by majenkotech** [comment]
I think you misunderstand what this project is. It is merely a way of turning an ESP8266 into a wireless serial dongle with DTR control. Nothing to do with telnet to host, or setting up WiFi.

**Comment by kkberg** [comment]
Hello, in your Source Code is something about Port 24 for configuring with telnet. That is what I mean. May be I misunderstood. My Intention is to configure without flashing ssid new, when using another WiFi. All over it works pretty good

**Comment by majenkotech** [comment]
Port 24 is RFC2217 which allows configuring of the *serial port* only - i.e., the baud rate. Nothing to do with WiFi. That is all hard coded.

* https://tools.ietf.org/html/rfc2217

**Comment by kkberg** [comment]
Okay , Thank you.

**Comment by kkberg** [comment]
One last question. As I understood I open a serial connection to the ESP with the Arduino IDE serial monitor and I get a response with OK. I type in for example show_settings. But there is no response from server then. I'm very new with all this stuff and there for I'm asking for a short help. It would be very kind if you would help me out describing how to use it. Thank you very much.

**Comment by majenkotech** [comment]
That is not a topic for here. Am I right in thinking you have bought an ESP8266 module and wired it to the Arduino, and not much else? The module probably came with the AT command set firmware. 

* https://www.espressif.com/sites/default/files/documentation/4a-esp8266_at_instruction_set_en.pdf

**Comment by kkberg** [comment]
No, I already have the serial port running with your sketch and it provides a serial port over wifi for my 3D printer. The ESP8266-01S came empty. I can connect to the printer using IP:23. This works pretty good and I only wanted to get an option to change wifi settings without having it hard coded. Then I red something about TELNET in the source and I asked for it with my first question. As I understand that isn't possible. So I'm now trying to to find a solution with a config file stored with using spiffs. I'm in the phase of leraning all this stuff and it's quite a hard job for an old retired person. So, I'm no longer disturbing you and thank you very much for your help.

**Comment by majenkotech** [comment]
This may be of more interest to you:

* https://github.com/tzapu/WiFiManager
